backend:
  name: git-gateway
  branch: main

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "frames"
    label: "Frames"
    folder: "content/frames"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Text", name: "text", widget: "string" }
